Feature/83 create dist build pipe
dopeshot/nextparty.io-frontend pull request #84
Opened 2022-09-23 09:15 UTC by LarsFlieger

- Add simple pipeline which builds the frontend and uploads it as artifact
- Removes testing pipe which is not working correctly ( Continue work in #66 )

2022-09-23 12:47 UTC, coffemakingtoaster requested changes

2022-09-23 12:47 UTC, coffemakingtoaster commented on .github/workflows/build.yml
> +        npm ci
Soweit ich weiß installiert ci auch dev dependencies, die haben hier aber nichts verloren, entsprechend `--production` benutzen

2022-09-23 12:47 UTC, coffemakingtoaster commented on .github/workflows/build.yml
> +      uses: actions/checkout@v2
actions/checkout ist bei v3  wenn ich nicht irre, gibt es einen Grund warum hier v2 verwendet wird?

2022-09-23 12:47 UTC, coffemakingtoaster commented on .github/workflows/build.yml
> +        npm ci
Alternativ kann auch die ENV variable dafür gesetzt werden, die weiß ich aber nicht auswendig

2022-09-23 12:47 UTC, coffemakingtoaster commented on .github/workflows/build.yml
> +          !build/**/*.md
Warum ist markdown included?

2022-09-24 20:59 UTC, LarsFlieger commented on .github/workflows/build.yml
> +      uses: actions/checkout@v2
Auf v3 gewechselt.

2022-09-24 21:00 UTC, LarsFlieger commented on .github/workflows/build.yml
> +        npm ci
Gute Idee!

2022-09-24 21:00 UTC, LarsFlieger commented on .github/workflows/build.yml
> +          !build/**/*.md
Ich meinte ! excluded etwas aber ja brauchen wir eingentlich nicht. Im React build ist kein markdown.

2022-09-26 08:27 UTC, coffemakingtoaster approved these changes
LGTM!
In the future we may want to add npm audit stage, but as a solution until tests work again this should be fine :D
great job 👍

2022-09-26 18:30 UTC, LarsFlieger commented
> npm audit stage

Gute Idee :)

2022-09-26 18:30 UTC, merged